language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
branches:
  only:
    - luaTable
cache:
  directories:
    - .cache
script:
  - mkdir output
  - make all
deploy:
  provider: pages
  name: MZI
  email: macchenjl@foxmail.com
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local-dir: output
  on:
    repo: MZIchenjl/kcwiki_bot
    branch: luaTable
